// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNoSVzvlft4fChbFULFWP6IdISzDajio',
    appId: '1:1042570688367:web:07e9695cc4613776309a9a',
    messagingSenderId: '1042570688367',
    projectId: 'hello-flutter-fire-49b5c',
    authDomain: 'hello-flutter-fire-49b5c.firebaseapp.com',
    storageBucket: 'hello-flutter-fire-49b5c.firebasestorage.app',
    measurementId: 'G-FPY6MY496P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7Gu2e3hm92hrSdYTKol12D66-oMtkrE',
    appId: '1:1042570688367:android:341911a80e07eebc309a9a',
    messagingSenderId: '1042570688367',
    projectId: 'hello-flutter-fire-49b5c',
    storageBucket: 'hello-flutter-fire-49b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMNvBBPlci2RzmT4mopVSb2d1gPHS8Y4',
    appId: '1:1042570688367:ios:62b7fbf8121e3b36309a9a',
    messagingSenderId: '1042570688367',
    projectId: 'hello-flutter-fire-49b5c',
    storageBucket: 'hello-flutter-fire-49b5c.firebasestorage.app',
    iosBundleId: 'com.example.medApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMNvBBPlci2RzmT4mopVSb2d1gPHS8Y4',
    appId: '1:1042570688367:ios:62b7fbf8121e3b36309a9a',
    messagingSenderId: '1042570688367',
    projectId: 'hello-flutter-fire-49b5c',
    storageBucket: 'hello-flutter-fire-49b5c.firebasestorage.app',
    iosBundleId: 'com.example.medApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNoSVzvlft4fChbFULFWP6IdISzDajio',
    appId: '1:1042570688367:web:bacdf19658504bc9309a9a',
    messagingSenderId: '1042570688367',
    projectId: 'hello-flutter-fire-49b5c',
    authDomain: 'hello-flutter-fire-49b5c.firebaseapp.com',
    storageBucket: 'hello-flutter-fire-49b5c.firebasestorage.app',
    measurementId: 'G-K6YL4YN9W7',
  );
}
